// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2K9eBK6_yQD0XKwEGD6XE0PybfMcPaVA',
    appId: '1:130411930818:web:fc3d3613da562adb91c75b',
    messagingSenderId: '130411930818',
    projectId: 'community-classroom-859bb',
    authDomain: 'community-classroom-859bb.firebaseapp.com',
    storageBucket: 'community-classroom-859bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXT1u_Rv5xZfd1WCUZ6xsVthaxLJ-zDP0',
    appId: '1:130411930818:android:99af5df930ac211391c75b',
    messagingSenderId: '130411930818',
    projectId: 'community-classroom-859bb',
    storageBucket: 'community-classroom-859bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhoQjRkqUcatVAjIPtSZlnEQudHV_Zmc0',
    appId: '1:130411930818:ios:6dd617d864dbc70e91c75b',
    messagingSenderId: '130411930818',
    projectId: 'community-classroom-859bb',
    storageBucket: 'community-classroom-859bb.appspot.com',
    iosBundleId: 'com.example.communityClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhoQjRkqUcatVAjIPtSZlnEQudHV_Zmc0',
    appId: '1:130411930818:ios:641626a20239296b91c75b',
    messagingSenderId: '130411930818',
    projectId: 'community-classroom-859bb',
    storageBucket: 'community-classroom-859bb.appspot.com',
    iosBundleId: 'com.example.communityClassroom.RunnerTests',
  );
}
